import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "../components/header";
import { ClientProvider } from "@/context/ClientContext";
import { MessageBeta } from "@/components/messageBeta";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <ClientProvider>
          <NavBar />
          {children}
          <MessageBeta />
        </ClientProvider>
      </body>
    </html>
  );
}
